name: weather_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.3
  geolocator: 14.0.0
  geocoding: ^2.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    # images for the app logos 
    - assets/appLogo/location_on.svg
    - assets/appLogo/search_locations.svg
    - assets/appLogo/sun_uvIndex.svg
    - assets/appLogo/temperature_feelsLike.svg
    - assets/appLogo/drop_humidity.svg
    - assets/appLogo/wind-speed.svg
    - assets/appLogo/wind_direction.svg
    - assets/appLogo/visibility_eye.svg
    - assets/appLogo/humidity_drop.svg
    - assets/appLogo/pressure_icon.svg
    - assets/appLogo/loading_page.png 
    - assets/appLogo/footer_logo.png
    - assets/appLogo/app_logo.png

    # images for the weather forecast
    - assets/weatherLogo/200-232.svg
    - assets/weatherLogo/233.svg
    - assets/weatherLogo/300-302.svg
    - assets/weatherLogo/500.svg
    - assets/weatherLogo/501-502.svg
    - assets/weatherLogo/511-522.svg
    - assets/weatherLogo/600-602_621-623.svg
    - assets/weatherLogo/611-612.svg
    - assets/weatherLogo/700_741-751.svg
    - assets/weatherLogo/711.svg
    - assets/weatherLogo/800.svg
    - assets/weatherLogo/801.svg
    - assets/weatherLogo/802.svg
    - assets/weatherLogo/803-804.svg
    - assets/weatherLogo/smiley-default.svg

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/jura/Jura-Light.ttf
          weight: 300
        - asset: assets/fonts/jura/Jura-Regular.ttf
          weight: 400
        - asset: assets/fonts/jura/Jura-Medium.ttf
          weight: 500
        - asset: assets/fonts/jura/Jura-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jura/Jura-Bold.ttf
          weight: 700

    - family: Michroma
      fonts:
        - asset: assets/fonts/michroma/Michroma-Regular.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appLogo/app_logo.png"
